using UnityEditor;
using MRuby.CodeGen;
using System.IO;

[InitializeOnLoad]
public class UnityCodeGen
{
    [MenuItem("MRuby/Generate Code")]
    static public void GenerateCode()
    {
        var opt = new MRubyCodeGen.Option
        {
            OutputDir = "Assets/mruby-unity/AutoGenerated/",
        };
        MRubyCodeGen.Run(opt);

        AssetDatabase.Refresh();
    }

    [MenuItem("MRuby/Clean")]
    static public void Clean()
    {
        Directory.Delete("Assets/mruby-unity/AutoGenerated", true);
        AssetDatabase.Refresh();
    }
}
